### ISSUE TITLE
Multiple jars named "sink"

### ISSUE THREAD

**Issue by matthewrj** [GoogleCloudPlatform/cloud-trace-java#80]
There are two transitve dependencies named "sink":
- com.google.cloud.trace.v1 » sink
- com.google.cloud.trace » sink

This causes issues with packaging an app as they both get downloaded into a lib folder and so one overwrites the other.

**Comment by erikmcc** [comment]
Interesting. I'm curious, what's your use case? Is it possible for your utility that copies the jars to rename them?

**Comment by matthewrj** [comment]
It's a gradle project and I'm using the ['application' plugin](https://docs.gradle.org/current/userguide/application_plugin.html). It probably is possible to rename lib files, but it would be a lot more convenient if it you didn't need to.

**Comment by erikmcc** [comment]
I think it's reasonable to rename this to api-sink.

**Comment by neonmori** [comment]
I'm having the same issue. In our production environment, we are putting all the dependencies into one directory, and 2 sink.jar will create some conflicts and the result is NoClassDefFoundError, com/google/cloud/trace/v1/util/Sizer is not found. Apparently, trace/v1/sink has been over-written by trace/sink.

**Comment by erikmcc** [comment]
We'll accept pull requests, if anyone is interested in doing this.

**Comment by henrylawson** [comment]
What is the workaround for this today?

**Comment by twistedpair** [comment]
Looks like the `tar` and `war` Gradle plugins allow applying a `duplicatesStrategy` as shown in this [discussion](https://discuss.gradle.org/t/dependencies-with-conflicting-name-version-jar-filenames/23344/2).

However, we're using the `distTar` task, and the `distribution` plugin has no such features. There is also the [`shadow`](http://imperceptiblethoughts.com/shadow/#configuring_shadowed_dependencies) plugin, but AFAICT, it only allows changing package names, not jar names, which is the problem here.

The Google team should prioritize this defect as this naming flaw prevents applications from being deployed to services like GKE or GCE in a fat jar. Hopefully this can be addressed soon by the Google team.

**WorkAround**:
* Copy the [two](http://repo1.maven.org/maven2/com/google/cloud/trace/sink/0.3.2/) [jars](http://repo1.maven.org/maven2/com/google/cloud/trace/v1/sink/0.3.2/) into your tar and rename them by hand to non-conflicting names
* Repeat every compile :smile:

**Comment by StdVectorBool** [comment]
I can submit a PR to modify the artifactId and fix up dependencies.

@erikmcc to clarify, I should rename the artifact in `sdk/sink/pom.xml` to `api-sink` (since it is a dependency of `sinks/v1/sink/pom.xml`)?

**Comment by twistedpair** [comment]
@StdVectorBool, any progress on the PR? It would be very helpful.

**Comment by erikmcc** [comment]
@bogdandrutu please provide guidance on this.

**Comment by bogdandrutu** [comment]
@StdVectorBool you are correct, please sent a PR, I will be back in the office Monday and can approve + release the new artifacts if needed.

**Comment by japgolly** [comment]
Just submitted #87. Is that what you had in mind? Tests pass locally.

**Comment by japgolly** [comment]
(Btw @bogdandrutu before you release new artefacts, would accept PRs that upgrade used versions of grpc, netty-boringssl, google oath2 as well?)

**Comment by StdVectorBool** [comment]
@japgolly Looks like you renamed the artifact in [sinks/v1/sink/pom.xml](https://github.com/GoogleCloudPlatform/cloud-trace-java/pull/87/files#diff-3f8229246e4787ad587086eb26b836c6).  I was trying to clarify with @erikmcc and @bogdandrutu in earlier post if `api-sink` should be the name of the more abstract artifact `sdk/sink/pom.xml` since it was actually being [used as a dependency](https://github.com/japgolly/cloud-trace-java/blob/d963e95c0a2669602e0e98e95387170661437a41/sinks/v1/sink/pom.xml#L59).

**Comment by bogdandrutu** [comment]
@japgolly sure, please send a PR
